name: shutdown operator pipeline

on:
  push:

jobs:
  validateKubernetesManifests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: validate manifests in ./deploy directory
        uses: instrumenta/kubeval-action@master
        with:
          files: ./deploy


  validateHelmCharts:
    needs: validateKubernetesManifests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Kubernetes tools
        uses: grebois/kube-tools@v1.5.2
        with:
          kubectl: 1.20.7
          kustomize: 3.5.5
          helm: 2.16.7
          helmv3: 3.2.1
          kubeseal: 0.12.5
          kubeaudit: 0.11.5
          command: |
            echo "Run kubeval for manifests"
            kubeval --strict --ignore-missing-schemas -d ./deploy/
            echo "Run kubeval for helm"
            helmv3 template ./helm | kubeval --strict --ignore-missing-schemas



  buildDocker:
    needs: validateHelmCharts
    runs-on: ubuntu-latest
    env:
      APP_NAME: djkormo-shutdown-operator

    steps:
    - uses: actions/checkout@v2

    - name: Publish to Docker Repository
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: djkormo/shutdown-operator
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: Dockerfile
        workdir: .
        
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'djkormo/shutdown-operator'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
